<?php
$key = $block->getCaptchaApiKey();
$shouldCheckCaptcha = $block->shouldCheckCaptcha();
$captchaType = $block->getCaptchaType();
if ($captchaType === 'google_captcha' && $shouldCheckCaptcha) : ?>
    <script src="https://www.google.com/recaptcha/api.js" ></script>
    <script type="text/x-magento-init">
        {
            "#newsletter-validate-detail": {
                "Smaily_SmailyForMagento/js/captcha": {
                    "id" : "smaily_recaptcha_1",
                    "key" : "<?= $key ?>"
                }
            }
        }
    </script>
<?php endif; ?>
