<div class="block newsletter">
    <div class="title"><strong>Newsletter</strong></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <label class="label" for="newsletter"><span><?php /* @escapeNotVerified */ echo __('Sign Up for Our Newsletter:') ?></span></label>
                <div class="control">
                    <input name="email" type="email" id="newsletter" placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>" data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="field newsletter_name" style="margin-top:10px;">
                <div class="control name" style="width:60%; display:inline-block; top:1px;position: relative;">
                    <input name="name"  type="text" id="nname" placeholder="<?php /* @escapeNotVerified */ echo __('Enter your name') ?>" data-validate="{required:true}"/>
                </div>
                <style>
                    .block.newsletter .field .control.name::before{ content:'\e627'; }
                </style>
                <button class="action subscribe primary" style="float:right;border-radius:4px;" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                    <span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
